import type { JournalState } from "./types";

const t1 = "2026-03-18T09:00:00.000Z";
const t2 = "2026-08-22T11:20:00.000Z";
const t3 = "2026-08-29T08:10:00.000Z";

export const SEED: JournalState = {
  books: [
    {
      id: "book-scarcity",
      title: "결핍은 우리를 어떻게 변화시키는가",
      author: "샌딜 멀레이너선 · 엘다 샤퍼",
      subtitle: "너무 적은 것이 너무 많은 것을 앗아가는 방식",
      coverTone: 0,
      createdAt: t1,
      updatedAt: t3,
    },
    {
      id: "book-thinking",
      title: "생각에 관한 생각",
      author: "대니얼 카너먼",
      subtitle: "빠른 직관과 느린 이성",
      coverTone: 1,
      createdAt: t2,
      updatedAt: t2,
    },
  ],
  sessions: [
    {
      id: "ses-scarcity-1",
      bookId: "book-scarcity",
      passNumber: 1,
      title: "결핍이 주의를 점령하는 방식",
      intent: "핵심 개념을 저자의 언어로 붙잡고, 내 삶의 결핍이 어디에 있는지 본다.",
      createdAt: t1,
      source: "manual",
    },
    {
      id: "ses-scarcity-2",
      bookId: "book-scarcity",
      passNumber: 2,
      title: "재독 — 슬랙을 설계로 옮기다",
      intent: "1회독의 개념을 실행 가능한 규칙으로 바꾸고, 다른 책과 잇는다.",
      createdAt: t3,
      source: "conversation",
    },
    {
      id: "ses-thinking-1",
      bookId: "book-thinking",
      passNumber: 1,
      title: "대역폭이 줄어들 때 시스템은 어떻게 실패하는가",
      intent: "결핍의 터널링을 시스템 1의 언어로 다시 읽는다.",
      createdAt: t2,
      source: "manual",
    },
  ],
  ideas: [
    {
      id: "idea-tunneling",
      title: "터널링",
      summary:
        "결핍은 주의를 한 곳에 고정시킨다. 당장의 구멍은 잘 보이지만, 구멍 밖의 중요한 일은 시야에서 사라진다.",
      tags: ["주의", "결핍"],
      createdAt: t1,
      updatedAt: t3,
    },
    {
      id: "idea-bandwidth",
      title: "대역폭 세금",
      summary:
        "부족한 상태는 인지 자원을 계속 거둬 간다. 지능이 낮아진 것이 아니라, 쓸 수 있는 머리가 이미 점유된 것이다.",
      tags: ["인지", "빈곤", "바쁨"],
      createdAt: t1,
      updatedAt: t2,
    },
    {
      id: "idea-slack",
      title: "슬랙을 설계한다",
      summary:
        "여유는 낭비가 아니라 충격 흡수 장치다. 시간·돈·주의에 의도적인 빈칸이 있어야 터널 밖을 볼 수 있다.",
      tags: ["여유", "시스템", "실행"],
      createdAt: t3,
      updatedAt: t3,
    },
    {
      id: "idea-system1",
      title: "점유된 직관",
      summary:
        "인지 자원이 줄면 시스템 1이 더 크게 말한다. 결핍은 성격을 바꾸는 것이 아니라, 어떤 생각이 이기게 할지를 바꾼다.",
      tags: ["직관", "판단"],
      createdAt: t2,
      updatedAt: t2,
    },
  ],
  entries: [
    {
      id: "e1",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-1",
      kind: "excerpt",
      title: "결핍은 마음을 사로잡는다",
      body: "저자들은 돈, 시간, 칼로리, 관계처럼 형태는 달라도 결핍의 심리는 같다고 본다. 부족한 것은 주의를 끌어당기고, 그 끌림은 당장의 문제를 푸는 집중(포커싱 배당)을 주지만 동시에 나머지 세계를 가린다.",
      tags: ["결핍", "주의"],
      ideaIds: ["idea-tunneling"],
      createdAt: t1,
      updatedAt: t1,
    },
    {
      id: "e2",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-1",
      kind: "excerpt",
      title: "대역폭, 그리고 세금",
      body: "유동 지능과 자기통제를 합쳐 대역폭이라 부른다. 결핍은 이 대역폭에 지속적인 세금을 매긴다. 가난한 사람이 나쁜 결정을 내리는 것이 아니라, 나쁜 결정이 나오기 쉬운 인지 상태에 놓인 것이다.",
      tags: ["대역폭"],
      ideaIds: ["idea-bandwidth"],
      createdAt: t1,
      updatedAt: t1,
    },
    {
      id: "e3",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-1",
      kind: "thought",
      title: "나는 돈이 아니라 시간에 터널링되어 있다",
      body: "빈 칸을 보면 바로 채워 넣는 버릇이 있다. 일정 앱의 하얀 블록이 결핍의 구멍처럼 느껴진다. 책을 읽으며 깨달은 것은, 나의 ‘바쁨’이 성실함이 아니라 슬랙을 견디지 못하는 상태일 수 있다는 점이다.",
      tags: ["바쁨", "시간"],
      ideaIds: ["idea-tunneling", "idea-slack"],
      createdAt: t1,
      updatedAt: t1,
    },
    {
      id: "e4",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-1",
      kind: "idea",
      title: "중요한 결정은 결핍 밖에서 한다",
      body: "돈이 빠듯한 날, 마감 전날, 잠이 부족한 날에는 ‘수긍하고 넘어가는’ 결정을 금지하는 규칙을 두면 어떨까. 터널 안에서는 협상하지 않고, 슬랙이 있는 다음 날 오전으로 미룬다.",
      tags: ["규칙", "결정"],
      ideaIds: ["idea-tunneling", "idea-slack"],
      createdAt: t1,
      updatedAt: t1,
    },
    {
      id: "e5",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-1",
      kind: "action",
      title: "수요일 오전에 빈 블록 두 시간을 고정한다",
      body: "매주 수요일 9–11시를 ‘슬랙’으로 잠근다. 회의도, 할 일도 넣지 않는다. 이 시간이 침범당하면 다음 주로 이월하지 않고 같은 주 안에 다른 빈칸을 다시 만든다.",
      tags: ["슬랙", "일정"],
      ideaIds: ["idea-slack"],
      createdAt: t1,
      updatedAt: t1,
    },
    {
      id: "e6",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-2",
      kind: "excerpt",
      title: "결핍의 함정은 미래의 대역폭을 담보 잡는다",
      body: "급할 때 빌리면 당장은 숨이 트이지만, 이자가 다음 주의 슬랙을 잡아먹는다. 시간 빚(벼락치기, 야근)도 같은 구조다. 함정은 의지의 문제가 아니라 구조의 문제다.",
      tags: ["함정", "빚"],
      ideaIds: ["idea-bandwidth"],
      createdAt: t3,
      updatedAt: t3,
    },
    {
      id: "e7",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-2",
      kind: "thought",
      title: "1회독 때는 ‘내가 게을러서’라고 읽었다",
      body: "다시 읽으니 초점이 바뀐다. 자책이 아니라 설계의 문제. 슬랙이 없는 주간 계획 자체가 결핍을 재생산하고 있었다. 지난번에 적어 둔 수요일 블록을 세 번 중 한 번만 지켰다는 사실이 증거다.",
      tags: ["재독", "자책"],
      ideaIds: ["idea-slack"],
      createdAt: t3,
      updatedAt: t3,
    },
    {
      id: "e8",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-2",
      kind: "idea",
      title: "여백은 남는 자리가 아니라 지키는 자리",
      body: "책의 ‘슬랙’을 이 앱의 이름과 겹쳐 본다. 읽기의 여백 — 내용과 생각 사이, 책과 책 사이, 회독과 회독 사이 — 를 비워 두지 않으면 모든 문장이 할 일이 된다. 기록도 결핍의 터널이 될 수 있다.",
      tags: ["여백", "기록"],
      ideaIds: ["idea-slack", "idea-tunneling"],
      createdAt: t3,
      updatedAt: t3,
    },
    {
      id: "e9",
      bookId: "book-scarcity",
      sessionId: "ses-scarcity-2",
      kind: "action",
      title: "큰 약속 전에 ‘대역폭 점검’ 세 줄",
      body: "새로운 일·모임·구매 전에 적는다. 1) 이번 주 슬랙이 남아 있는가 2) 이것을 넣으면 무엇을 밀어내는가 3) 터널 안에서 결정하는 것은 아닌가. 세 줄이 비어 있으면 하지 않는다.",
      tags: ["점검", "약속"],
      ideaIds: ["idea-bandwidth", "idea-slack"],
      createdAt: t3,
      updatedAt: t3,
    },
    {
      id: "e10",
      bookId: "book-thinking",
      sessionId: "ses-thinking-1",
      kind: "excerpt",
      title: "시스템 1은 이야기를 완성하려고 한다",
      body: "카너먼은 빠른 직관(시스템 1)이 부족한 정보를 메워 일관된 이야기를 만든다고 한다. 확신은 증거의 양이 아니라 이야기의 완결감에서 온다.",
      tags: ["시스템1"],
      ideaIds: ["idea-system1"],
      createdAt: t2,
      updatedAt: t2,
    },
    {
      id: "e11",
      bookId: "book-thinking",
      sessionId: "ses-thinking-1",
      kind: "idea",
      title: "결핍은 시스템 1의 볼륨을 높인다",
      body: "멀레이너선의 대역폭 세금과 카너먼의 이중 과정을 겹치면: 결핍은 시스템 2의 예산을 줄여, 완결된 이야기에 더 쉽게 넘어가게 한다. 바쁠 때의 과신은 성격이 아니라 자원 배분의 결과일 수 있다.",
      tags: ["연결", "과신"],
      ideaIds: ["idea-system1", "idea-bandwidth"],
      createdAt: t2,
      updatedAt: t2,
    },
    {
      id: "e12",
      bookId: "book-thinking",
      sessionId: "ses-thinking-1",
      kind: "action",
      title: "확신이 클수록 반대 증거를 한 줄 적는다",
      body: "‘이건 확실해’라는 느낌이 드는 판단에는, 그 이야기가 빠뜨린 사실을 한 줄만 적고 나서 움직인다. 터널 밖을 한 줄로 강제하는 장치.",
      tags: ["판단", "습관"],
      ideaIds: ["idea-system1", "idea-tunneling"],
      createdAt: t2,
      updatedAt: t2,
    },
  ],
};
