/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MapRouteImport } from './routes/map'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasRoute,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => IdeasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/ideas': typeof IdeasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/import': typeof ImportRoute
  '/map': typeof MapRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/import'
    | '/map'
    | '/books/$bookId'
    | '/ideas/$ideaId'
    | '/ideas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/import' | '/map' | '/books/$bookId' | '/ideas/$ideaId' | '/ideas'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/import'
    | '/map'
    | '/books/$bookId'
    | '/ideas/$ideaId'
    | '/ideas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  ImportRoute: typeof ImportRoute
  MapRoute: typeof MapRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof IdeasRoute
    }
  }
}

interface IdeasRouteChildren {
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRoute: IdeasRouteWithChildren,
  ImportRoute: ImportRoute,
  MapRoute: MapRoute,
  BooksBookIdRoute: BooksBookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
